### ISSUE TITLE
No color option for info boxes in shinyDashboardThemeDIY

### ISSUE THREAD

**Issue by jameszak** [nik01010/dashboardthemes#12]
It seems to me that `shinyDashboardThemeDIY` allows you to set the colors for the small colored status bar on top of boxes for all status types except for "info". I expected a sixth line in the below snippet for boxInfoColor, but it isn't an option. This seems consistent across several functions, so it is probably intentional but I can't tell why.

```
    ,boxDefaultColor = "rgb(210,214,220)"
    ,boxPrimaryColor = "rgba(44,222,235,1)"
    ,boxSuccessColor = "rgba(0,255,213,1)"
    ,boxWarningColor = "rgb(244,156,104)"
    ,boxDangerColor = "rgb(255,88,55)"
```

**Comment by nik01010** [comment]
Thanks for spotting this. A new release v1.0.4 has been created to add this functionality in Pull Request #13
