### ISSUE TITLE
Is it possible to change the font color of a box Panel?

### ISSUE THREAD

**Issue by martinbel** [nik01010/dashboardthemes#16]
I have the following panel. I was able to change the box color but I can't change the box title color! 
I'd like to change the title of all boxes to white. Is this possible in the current DIY theme?

![image](https://user-images.githubusercontent.com/4535400/57022637-1f2a9a00-6c06-11e9-80d4-964c18643ecd.png)

This is my custom theme: 

`shinyDashboardThemeDIY(
      
      ### general
      appFontFamily = "Arial"
      ,appFontColor = "rgb(0,0,0)"
      ,primaryFontColor = "rgb(0,0,0)"
      ,infoFontColor = "rgb(0,0,0)"
      ,successFontColor = "rgb(0,0,0)"
      ,warningFontColor = "rgb(0,0,0)"
      ,dangerFontColor = "rgb(0,0,0)"
      ,bodyBackColor = "rgb(255,255,255)"
      
      ### header
      ,logoBackColor = "rgb(255,255,255)"
      ,headerButtonBackColor = "rgb(255,255,255)"
      ,headerButtonIconColor = "rgb(255,255,255)"
      ,headerButtonBackColorHover = "rgb(255,255,255)"
      ,headerButtonIconColorHover = "rgb(0,0,0)"
      
      ,headerBackColor = "rgb(255,255,255)"
      ,headerBoxShadowColor = "rgb(255,255,255)"
      ,headerBoxShadowSize = "2px 3px 2px"
      
      ### sidebar
      ,sidebarBackColor = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "rgb(255,255,255)"
        ,colorMiddle = "rgb(255,255,255)"
        ,colorEnd = "rgb(255,255,255)"
        ,colorStartPos = 0
        ,colorMiddlePos = 97
        ,colorEndPos = 100
      )
      ,sidebarPadding = 0
      
      ,sidebarMenuBackColor = "transparent"
      ,sidebarMenuPadding = 0
      ,sidebarMenuBorderRadius = 0
      
      ,sidebarShadowRadius = "0px 0px 0px"
      ,sidebarShadowColor = ""
      
      ,sidebarUserTextColor = "rgb(0,0,0)"
      
      ,sidebarSearchBackColor = "rgb(255,255,255)"
      ,sidebarSearchIconColor = "rgb(255,255,255)"
      ,sidebarSearchBorderColor = "rgb(255,255,255)"
      
      ,sidebarTabTextColor = "rgb(0,0,0)"
      ,sidebarTabTextSize = 13
      ,sidebarTabBorderStyle = "none"
      ,sidebarTabBorderColor = ""
      ,sidebarTabBorderWidth = 0
      
      ,sidebarTabBackColorSelected = cssGradientThreeColors(
        direction = "down"
        ,colorStart = "rgb(255,255,255)"
        ,colorMiddle = "rgb(255,255,255)"
        ,colorEnd = "rgb(255,255,255)"
        ,colorStartPos = 0
        ,colorMiddlePos = 5
        ,colorEndPos = 100
      )
      ,sidebarTabTextColorSelected = "rgb(0,0,0)"
      ,sidebarTabRadiusSelected = "0px"
      
      ,sidebarTabBackColorHover = cssGradientThreeColors(
        direction = "right"
        ,colorStart = "rgb(230,230,230)"
        ,colorMiddle = "rgb(225,225,225)"
        ,colorEnd = "rgb(210,210,210)"
        ,colorStartPos = 0
        ,colorMiddlePos = 97
        ,colorEndPos = 100
      )
      ,sidebarTabTextColorHover = "rgb(0,0,0)"
      ,sidebarTabBorderStyleHover = "none"
      ,sidebarTabBorderColorHover = ""
      ,sidebarTabBorderWidthHover = 0
      ,sidebarTabRadiusHover = "0px"
      
      ### boxes
      ,boxBackColor = "rgb(255,255,255)"
      ,boxBorderRadius = 0
      ,boxShadowSize = "none"
      ,boxShadowColor = "rgb(255,255,255)"
      ,boxTitleSize = 18
      ,boxDefaultColor = "rgb(225,225,225)"
      ,boxPrimaryColor = "rgb(255,255,255)"
      ,boxInfoColor = "(11,152,203)"   # color tabs box
      ,boxSuccessColor = "rgb(255,255,255)"
      ,boxWarningColor = "rgb(255,255,255)"
      ,boxDangerColor = "rgb(255,255,255)"
      
      ,tabBoxTabColor = "rgb(255,255,255)"
      ,tabBoxTabTextSize = 14
      ,tabBoxTabTextColor = "rgb(255,255,255)"
      ,tabBoxTabTextColorSelected = "rgb(255,255,255)"
      ,tabBoxBackColor = "rgb(255,255,255)"
      ,tabBoxHighlightColor = "rgb(210,210,210)"
      ,tabBoxBorderRadius = 0
      
      ### inputs
      ,buttonBackColor = "rgb(240,240,240)"
      ,buttonTextColor = "rgb(80,80,80)"
      ,buttonBorderColor = "rgb(185,185,185)"
      ,buttonBorderRadius = 5
      
      ,buttonBackColorHover = "rgb(227,227,227)"
      ,buttonTextColorHover = "rgb(80,80,80)"
      ,buttonBorderColorHover = "rgb(210,210,210)"
      
      ,textboxBackColor = "rgb(255,255,255)"
      ,textboxBorderColor = "rgb(210,210,210)"
      ,textboxBorderRadius = 0
      ,textboxBackColorSelect = "rgb(255,255,255)"
      ,textboxBorderColorSelect = "rgb(210,210,210)"
      
      ### tables
      ,tableBackColor = "rgb(255,255,255)"
      ,tableBorderColor = "rgb(255,255,255)"
      ,tableBorderTopSize = 1
      ,tableBorderRowSize = 1
    )`

**Comment by nik01010** [comment]
You should be able to change the title colour of boxes using these parameters:

      ,primaryFontColor = "rgb(0,0,0)"
      ,infoFontColor = "rgb(0,0,0)"
      ,successFontColor = "rgb(0,0,0)"
      ,warningFontColor = "rgb(0,0,0)"
      ,dangerFontColor = "rgb(0,0,0)"
