### ISSUE TITLE
Is there way to add a "none" theme

### ISSUE THREAD

**Issue by Sanrrone** [nik01010/dashboardthemes#18]
Hi, I'm playing with the module to set the choices for the different themes available, but I cannot to set the theme "none", I mean reset the theme with the shinydashboard defaults , I tried to add the default option with different values but none of them restore the shinydashboard.

Is there a way to add an option and set none theme?

```
  changeThemeChoices <- c(
    "Default" = NA, # NA, NULL, "", "none"
    "Blue gradient" = "blue_gradient",
    "BoE website" = "boe_website",
    "Grey light" = "grey_light",
    "Grey dark" = "grey_dark",
    "OneNote" = "onenote",
    "Poor man's Flatly" = "poor_mans_flatly",
    "Purple gradient" = "purple_gradient"
  )
```

regards

**Comment by nik01010** [comment]
Hi Sanrrone,
When you "select" a theme, the package injects CSS styles into the app, therefore overriding the original shinydashboard blue theme settings. If you want to revert back to the original theme, you would need to inject its CSS styles into the app again. I believe those styles may be stored in a .css file somewhere in the official shiny/dashboard packages. Selecting "Default" in your drop-down would then need to trigger an alternative action where you bypass the dashboardthemes package and restore the default shiny theme instead via some custom code.

**Comment by Sanrrone** [comment]
thanks you sir, I'll try it.
