### ISSUE TITLE
Package checks

### ISSUE THREAD

**Issue by erykwalczak** [nik01010/dashboardthemes#3]
I ran the checks on the package in RStudio and I got 1 error and 2 notes. You might want to fix them if you are thinking about putting dashboardthemes on CRAN.

> * checking for missing documentation entries ... WARNING
> Undocumented code objects:
>   ‘logo_blue_gradient’ ‘logo_boe_website’ ‘logo_grey_dark’
>   ‘logo_grey_light’ ‘logo_onenote’ ‘logo_poor_mans_flatly’
>   ‘logo_purple_gradient’ ‘theme_blue_gradient’ ‘theme_boe_website’
>   ‘theme_grey_dark’ ‘theme_grey_light’ ‘theme_onenote’
>   ‘theme_poor_mans_flatly’ ‘theme_purple_gradient’
> * checking for unstated dependencies in examples ... WARNING
> Warning: parse error in file 'dashboardthemes-Ex.R':
> 5: unexpected symbol
> 53:     )
> 54:     ...
> * checking examples ... ERROR
> Running examples in ‘dashboardthemes-Ex.R’ failed

Later, I used [goodpractice](https://github.com/MangoTheCat/goodpractice) to check your package and found quite a lot of notes. They were mostly about the lack of unit tests, using `<-` instead of `=` for assignments, and avoiding long lines of code. There were too many of those cases to list here but it might be worth addressing them. This will make your code more readable and will follow good practices.

**Comment by nik01010** [comment]
The above issues have (very) belatedly been fixed in PR #21 , ahead of the next release.
