### ISSUE TITLE
Change back to default theme with selectInput

### ISSUE THREAD

**Issue by PhilippPro** [nik01010/dashboardthemes#35]
Hi! 
I love this package. I implemented a selectInput box with which I can choose the theme. Is there a possibility to switch back to the default shiny theme after switching to a theme with shinyDashboardThemes(theme = input$theme). 
Switching to other themes works nicely.

**Comment by nik01010** [comment]
Hi Philipp,
Unfortunately once you have switched on a custom theme, you have rendered css code on the web page and it's difficult to return back to the original shiny stock theme. You could try creating your own theme using the dashboardthemes package which uses the same colour scheme as the stock one, then it would be easy to switch back to it.
