### ISSUE TITLE
Is there a way to change the logo text in dashboardlogo function

### ISSUE THREAD

**Issue by vikram-rawat** [nik01010/dashboardthemes#4]
By default, it gives something that should be changed for every product.

**Comment by nik01010** [comment]
Yes, it's possible to change the logo text using shinyDashboardLogoDIY - try something like the below. More information is available in the documentation for this function.

...
  dashboardHeader(

    title = shinyDashboardLogoDIY(
      boldText = "Example"
      ,mainText = "Logo"
      ,textSize = 16
      ,badgeText = "BETA"
      ,badgeTextColor = "white"
      ,badgeTextSize = 2
      ,badgeBackColor = "#40E0D0"
      ,badgeBorderRadius = 3
    )

  )
...

**Comment by vikram-rawat** [comment]
Thanks for replying


I tried that but I could not remove the badge.

Is there a way to do that TOO... Please

शुक्र, 20 अप्रैल 2018, 11:17 pm को Nik L <notifications@github.com> ने लिखा:

**Comment by nik01010** [comment]
I hadn't realised you want to remove the badge as well. For that, try the below:

    title = shinyDashboardLogoDIY(
      boldText = "Example"
      ,mainText = "Logo"
      ,textSize = 16
      ,badgeText = ""
      ,badgeTextColor = "none"
      ,badgeTextSize = "none"
      ,badgeBackColor = "none"
      ,badgeBorderRadius = "none"
    )

**Comment by vikram-rawat** [comment]
Thanks for replying I am okay with it.

It will get me going.

Thanks for that but don't you think first function should get a title
argument at least.

And thanks for creating such a great package needed it for a very long time.

शुक्र, 20 अप्रैल 2018, 11:24 pm को Nik L <notifications@github.com> ने लिखा:
