### ISSUE TITLE
Code to recreate dashboardthemes with fresh?

### ISSUE THREAD

**Issue by cknotz** [nik01010/dashboardthemes#44]
Dear Nik,

sad to see that `dashboardthemes` is not continued! 

Could you perhaps post instructions on how to recreate your themes with `fresh`? I understand of course if that's too much work!

Best
Carlo

**Comment by nik01010** [comment]
Hi Carlo,

Sorry, I don't have much time to create a mapping between the two packages.

The fresh package looks to have pretty good documentation, so I suggest looking at that for a start. They also have a good selection of themes themselves.

https://dreamrs.github.io/fresh/
https://dreamrs.github.io/fresh/reference/index.html
https://dreamrs.github.io/fresh/articles/vars-shinydashboard.html
