### ISSUE TITLE
Sidebar menuSubItem's Text Changes to Selected Color

### ISSUE THREAD

**Issue by RoboNautilus** [nik01010/dashboardthemes#9]
When adding menuSubItem's to the Sidebar and then clicking to expand the menu; all of the SubItems's text changes to sidebarTabTextColorSelected value. Is there a way to specify the color of these menuStubItem's?

I found where someone was able to solve this issue using the below code in the dashboardSidebar section, but it would be nice to set this in the shinyDashboardThemeDIY function.

tags$style(HTML(".main-sidebar .sidebar .sidebar-menu .treeview-menu li.active a {background-color: #1E282C !important;}")),
tags$style(HTML(".main-sidebar .sidebar .sidebar-menu .treeview-menu li:hover a {background-color: #1E282C !important;}"))

**Comment by nik01010** [comment]
The shinyDashboardThemeDIY function already includes the below code for changing the background colour of a selected menuSubItem. You can alter this via the sidebarTabBackColorSelected parameter. 

Is that what you're looking for?

          /* sidebar: subtab selected */
          .skin-blue .treeview-menu > li.active > a,
          .skin-blue .treeview-menu > li > a:hover {
            background: ', sidebarTabBackColorSelected, ';
          }
